package Day2;

public class understanding_throw_exceptions {
	public static void main(String[] args)
	{
		int[] arr = new int[4];
		arr[0]=1;
		try
		{
			arr[6]=6;
		}
		catch(IOException e)
		{
			e.printStackTrace();
		}
		System.out.println("passed exception");}

	}

